const products = [
    {
        "id":1,
        "image":"images/1.png",
        "name" : "2017 Aegidienberger",
        "birth":"2017",
        "breed":"Aegidienberger",
        "sex":"Mare",
        "height" : "14.2hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"2500",
        "age":"Foul",
        "suitability":"Dressage",
        "colour":"Brown",
        "country":"Albania",
        
    },
    {
        "id":2,
        "image":"images/2.jpg",
        "name" : "2020 Warmblood",
        "birth":"2020",
        "breed":"Warmblood",
        "sex":"Mare",
        "height" : "15hh",
        "dameSire":"Tiffany  Romellle",
        "sire":"",
        "price":"2500",
        "colour":"black",
        "discipline":"Eventing",
    },
    {
        "id":3,
        "image":"images/3.jpg",
        "name" : "Black Glamourdale Filly",
        "birth":"2017",
        "breed":"Black Glamourdale Filly",
        "sex":"Filly",
        "height" : "17hh",
        "dameSire":"Burggraaf",
        "sire":"Sire: Thuja",
        "price":"2500",
        "colour":"black",
        "discipline":"Dressage",
    },
    {
        "id":4,
        "image":"images/4.jpg",
        "name" : "Competitive TB jumper",
        "birth":"2017",
        "breed":"Competitive TB jumper",
        "sex":"Gelding",
        "height" : "16.1hh",
        "dameSire":"Silver Cachelle",
        "sire":"Domesday",
        "price":"2500",
        "colour":"Grey",
        "discipline":"Eventer"
    },
    {
        "id":5,
        "image":"images/5.png",
        "name" : "Arabian",
        "birth":"2017",
        "breed":"Aegidienberger",
        "sex":"",
        "height" : "14.2hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"2500"
    },
    {
        "id":6,
        "image":"images/6.png",
        "name" : "2021 Appaloosa",
        "birth":"2021",
        "breed":"Appaloosa",
        "sex":"Sex : Mare",
        "height" : "14.7hh",
        "dameSire":"Petite Nonette",
        "sire":"Oscar",
        "price":"2500"
    },
    {
        "id":7,
        "image":"images/7.png",
        "name" : "2019 Frescian",
        "birth":"2019",
        "breed":"Frescian",
        "sex":"Mare",
        "height" : "14.2hh",
        "dameSire":"Nonette",
        "sire":"Oscar",
        "price":"2500",
        

    },
{
    "id":8,
    "image":"images/8.jpg",
    "name" : "Henbury Cambridge",
    "birth":"2020",
    "breed":"Warmblood",
    "sex":"Gelding",
    "height" : "16.1hh",
    "dameSire":"Varese",
    "sire":"Cachassini",
    "price":"2500",
    "colour":"Brown",
    "discipline":"Jumping"
},
{
    "id":9,
    "image":"images/9.jpg",
    "name" : "2017 Pony",
    "birth":"2017",
    "breed":"Pony",
    "sex":"Gelding",
    "height" : "13.2hh",
    "dameSire":"Petite Nonette",
    "sire":"Oscar",
    "price":"2500",
    "colour":"Chestnut",
    "discipline":"Jumping"
},
{
    "id":10,
    "image":"images/1.png",
    "name" : "Horse",
    "birth":"2017",
    "breed":"Aegidienberger",
    "sex":"Mare",
    "height" : "14.2hh",
    "dameSire":"Roasted Aus",
    "sire":"Zinnia",
    "price":"2500"
}, 
{
    "id":11,
    "image":"images/1.png",
    "name" : "Horse",
    "birth":"2017",
    "breed":"Aegidienberger",
    "sex":"Mare",
    "height" : "14.2hh",
    "dameSire":"Caretino",
    "sire":"Cachas",
    "price":"2500"
},

{
    "id":12,
    "image":"images/1.png",
    "name" : "Horse",
    "birth":"2017",
    "breed":"Aegidienberger",
    "sex":"Mare",
    "height" : "14.2hh",
    "dameSire":"Ixion Kwpn",
    "sire":"Ulft",
    "price":"2500"
},
];

export default products;